basePath: /api/v1
host: 127.0.0.1:9995
info:
  contact: {}
  description: 文档描述略
  license: {}
  title: HelloC API (Swagger Example)
  version: "1.0"
paths:
  /{id}/upload/:
    post:
      consumes:
      - application/json
      description: 管理员
      parameters:
      - description: 视频id
        in: path
        name: id
        required: true
        type: string
      - description: 是否通过
        in: formData
        name: pass
        required: true
        type: boolean
      responses:
        "200":
          description: '{"message":"视频审核完成", "results":null}'
          schema:
            type: string
        "400":
          description: '{"msg": "视频审核失败!", "results": null}'
          schema:
            type: string
      summary: 审核视频
      tags:
      - 视频
  /auth/:
    post:
      consumes:
      - application/json
      description: 通过JWT验证账号密码，获取token
      parameters:
      - default: '{"name": "xiaoming", "password": "123456"}'
        description: name(*用户名) password(*密码)
        in: body
        name: body
        required: true
        schema:
          type: string
      responses:
        "200":
          description: '{"msg": "token生成成功!", "results": "tokenString"}'
          schema:
            type: string
        "400":
          description: '{"msg": "参数错误/token生成失败!/账号不存在或密码错误", "results": null}'
          schema:
            type: string
      summary: 登录认证
      tags:
      - 认证
  /auth2/:
    post:
      consumes:
      - application/json
      description: 用于Swagger，只做测试
      parameters:
      - default: '{"name": "xiaoming", "password": "123456"}'
        description: name(*用户名) password(*密码)
        in: body
        name: body
        required: true
        schema:
          type: string
      responses:
        "200":
          description: '{"msg": "token生成成功!", "results": "tokenString"}'
          schema:
            type: string
        "400":
          description: '{"msg": "参数错误/token生成失败!/账号不存在或密码错误", "results": null}'
          schema:
            type: string
      summary: 登录认证2，用于Swagger，只做测试
      tags:
      - 认证
  /users/:
    get:
      consumes:
      - application/json
      description: 暂时无权限/后需要登录
      parameters:
      - description: 页数
        in: query
        name: page
        type: string
      - description: 个数
        in: query
        name: size
        type: string
      responses:
        "200":
          description: '{"message":"成功获取用户列表!","results":[{"id":1,"nickname":"小明","account":"xiaoming","password":"123456","email":"","phone":"","isAdmin":false,"photoFile":"","createdTime":""}}]}'
          schema:
            type: string
        "400":
          description: '{"msg": "参数错误/获取用户列表失败!", "results": null}'
          schema:
            type: string
      summary: 获取用户列表
      tags:
      - 用户
    post:
      consumes:
      - application/json
      description: 只有管理员可以添加用户
      parameters:
      - default: '{"nickname": "小明", "account": "xiaom", "password": "123456", "email":
          "", "phone": "", "isAdmin": false, "photoFile":""}'
        description: 'account(*账号), passowrd(*密码) '
        in: body
        name: body
        required: true
        schema:
          type: string
      responses:
        "200":
          description: '{"message":"创建用户完成!","results":{"id":1,"nickname":"小明","account":"xiaoming","password":"123456","email":"","phone":"","isAdmin":false,"photoFile":"","createdTime":""}}}'
          schema:
            type: string
        "400":
          description: '{"msg": "参数错误/用户已存在，创建失败!", "results": null}'
          schema:
            type: string
      summary: 新增用户
      tags:
      - 用户
  /users/{id}/:
    delete:
      consumes:
      - application/json
      description: 只有管理员可以删除用户
      parameters:
      - description: 用户id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: '{"message":"删除完成！","results": null}'
          schema:
            type: string
        "400":
          description: '{"msg": "参数错误/删除失败!", "results": null}'
          schema:
            type: string
      summary: 删除用户
      tags:
      - 用户
    get:
      consumes:
      - application/json
      description: 登陆后才允许获取用户信息
      parameters:
      - description: 用户id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: '{"message":"成功获取用户!","results":{"id":1,"nickname":"小明","account":"xiaoming","password":"123456","email":"","phone":"","isAdmin":false,"photoFile":"","createdTime":""}}}'
          schema:
            type: string
        "400":
          description: '{"msg": "参数错误/用户不存在!", "results": null}'
          schema:
            type: string
      summary: 获取用户
      tags:
      - 用户
    put:
      consumes:
      - application/json
      description: 只有管理员/或用户自己可以修改
      parameters:
      - default: "1"
        description: 用户id
        in: path
        name: id
        required: true
        type: string
      - default: '{"nickname": "小明", "password": "123456", "email": "", "phone": ""}'
        description: 用户信息
        in: body
        name: body
        required: true
        schema:
          type: string
      responses:
        "200":
          description: '{"message":"成功修改用户!","results":{"id":1,"nickname":"小明","account":"xiaoming","password":"123456","email":"","phone":"","isAdmin":false,"photoFile":"","createdTime":""}}}'
          schema:
            type: string
        "400":
          description: '{"msg": "参数错误/用户不存在!/用户修改失败!", "results": null}'
          schema:
            type: string
      summary: 修改用户
      tags:
      - 用户
  /videos/:
    get:
      consumes:
      - application/json
      description: 无权限
      parameters:
      - description: 页数
        in: query
        name: page
        type: string
      - description: 个数
        in: query
        name: size
        type: string
      responses:
        "200":
          description: '{"message":"成功获取视频列表!","results":[{"id":1,"nickname":"小明","account":"xiaoming","password":"123456","email":"","phone":"","isAdmin":false,"photoFile":"","createdTime":""}}]}'
          schema:
            type: string
        "400":
          description: '{"msg": "参数错误/获取视频列表失败!", "results": null}'
          schema:
            type: string
      summary: 获取视频信息列表
      tags:
      - 视频
    post:
      consumes:
      - application/json
      description: 普通用户可上传
      parameters:
      - default: '{"title": "小明大战小黄", "desc": "test", "category": "电影", "label": "小明，小黄，动作，武打",
          "rm": "mp4"}'
        description: title(*标题)
        in: body
        name: body
        required: true
        schema:
          type: string
      responses:
        "200":
          description: '{"message":"创建视频完成!","results":{"id":1,"nickname":"小明","account":"xiaoming","password":"123456","email":"","phone":"","isAdmin":false,"photoFile":"","createdTime":""}}}'
          schema:
            type: string
        "400":
          description: '{"msg": "参数错误/创建失败!", "results": null}'
          schema:
            type: string
      summary: 上传视频信息
      tags:
      - 视频
  /videos/{id}/:
    delete:
      consumes:
      - application/json
      description: 只有管理员或作者可以删除视频
      parameters:
      - description: 视频id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: '{"message":"删除完成！","results": null}'
          schema:
            type: string
        "400":
          description: '{"msg": "参数错误/删除失败!", "results": null}'
          schema:
            type: string
      summary: 删除视频
      tags:
      - 视频
    get:
      consumes:
      - application/json
      parameters:
      - description: 视频id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: '{"message":"成功获取视频信息!","results":{"id":1,"nickname":"小明","account":"xiaoming","password":"123456","email":"","phone":"","isAdmin":false,"photoFile":"","createdTime":""}}}'
          schema:
            type: string
        "400":
          description: '{"msg": "参数错误/视频不存在!", "results": null}'
          schema:
            type: string
      summary: 获取视频信息
      tags:
      - 视频
    put:
      consumes:
      - application/json
      description: 只有管理员/或用户自己可以修改视频信息
      parameters:
      - default: '{"title": "小明大战小黄", "desc": "test", "category": "电影", "label": "小明，小黄，动作，武打",
          "rm": "mp4"}'
        description: title(*标题)
        in: body
        name: body
        required: true
        schema:
          type: string
      - default: '{"nickname": "小明", "account": "xiaoming", "password": "123456",
          "email": "", "phone": ""}'
        description: 用户信息
        in: body
        name: body
        required: true
        schema:
          type: string
      responses:
        "200":
          description: '{"message":"成功修改用户!","results":{"id":1,"nickname":"小明","account":"xiaoming","password":"123456","email":"","phone":"","isAdmin":false,"photoFile":"","createdTime":""}}}'
          schema:
            type: string
        "400":
          description: '{"msg": "参数错误/用户不存在!/用户修改失败!", "results": null}'
          schema:
            type: string
      summary: 修改视频
      tags:
      - 视频
swagger: "2.0"
