basePath: /api/v1
definitions:
  models.User:
    properties:
      account:
        description: 账号
        type: string
      createdTime:
        description: 创建时间
        type: string
      email:
        description: 邮箱
        type: string
      id:
        description: 用户id
        type: integer
      isAdmin:
        description: 是否是管理员
        type: boolean
      nickname:
        description: 名称
        type: string
      password:
        description: 密码
        type: string
      phone:
        description: 手机
        type: string
      photoFile:
        description: 用户头像
        type: string
    type: object
  utils.Response:
    properties:
      message:
        description: 返回说明
        type: string
      results:
        type: object
    type: object
  v1.AddUserParam:
    properties:
      account:
        description: 账号
        example: xiaom
        type: string
      createdTime:
        description: 创建时间
        example: ' '
        type: string
      email:
        description: 邮箱
        example: ' '
        type: string
      isAdmin:
        description: 是否是管理员
        example: false
        type: boolean
      nickname:
        description: 名称
        example: 小明
        type: string
      password:
        description: 密码
        example: "123456"
        type: string
      phone:
        description: 手机
        example: ' '
        type: string
      photoFile:
        description: 用户头像
        example: ' '
        type: string
    required:
    - account
    - nickname
    - password
    type: object
  v1.ModifyUserParam:
    properties:
      email:
        description: 邮箱
        example: ' '
        type: string
      nickname:
        description: 名称
        example: xiaom
        type: string
      password:
        description: 密码
        example: "123456"
        type: string
      phone:
        description: 手机
        example: ' '
        type: string
    required:
    - nickname
    - password
    type: object
  v1.TParam:
    properties:
      a:
        description: 字符串a
        example: a
        type: string
      b:
        description: 数字b
        example: 2
        type: integer
      c:
        description: 布尔c
        example: false
        type: boolean
    required:
    - a
    type: object
  v1.TResponse:
    properties:
      message:
        description: 成功返回说明
        type: string
      results:
        type: object
    type: object
  v1.TResponse2:
    properties:
      message:
        description: 错误返回说明
        type: string
      results:
        type: object
    type: object
host: 127.0.0.1:9995
info:
  contact: {}
  description: 文档描述略
  license: {}
  title: HelloC API (Swagger Example)
  version: "1.0"
paths:
  /{id}/upload/:
    post:
      consumes:
      - application/json
      description: 管理员
      parameters:
      - description: 视频id
        in: path
        name: id
        required: true
        type: string
      - description: 是否通过
        in: formData
        name: pass
        required: true
        type: boolean
      responses:
        "200":
          description: '{"message":"视频审核完成", "results":null}'
          schema:
            type: string
        "400":
          description: '{"msg": "视频审核失败!", "results": null}'
          schema:
            type: string
      summary: 审核视频
      tags:
      - 视频
  /auth/:
    post:
      consumes:
      - application/json
      description: 通过JWT验证账号密码，获取token
      parameters:
      - default: '{"name": "xiaoming", "password": "123456"}'
        description: name(*用户名) password(*密码)
        in: body
        name: body
        required: true
        schema:
          type: string
      responses:
        "200":
          description: '{"msg": "token生成成功!", "results": "tokenString"}'
          schema:
            type: string
        "400":
          description: '{"msg": "参数错误/token生成失败!/账号不存在或密码错误", "results": null}'
          schema:
            type: string
      summary: 登录认证
      tags:
      - 认证
  /auth2/:
    post:
      consumes:
      - application/json
      description: 用于Swagger，只做测试
      parameters:
      - default: '{"name": "xiaoming", "password": "123456"}'
        description: name(*用户名) password(*密码)
        in: body
        name: body
        required: true
        schema:
          type: string
      responses:
        "200":
          description: '{"msg": "token生成成功!", "results": "tokenString"}'
          schema:
            type: string
        "400":
          description: '{"msg": "参数错误/token生成失败!/账号不存在或密码错误", "results": null}'
          schema:
            type: string
      summary: 登录认证2，用于Swagger，只做测试
      tags:
      - 认证
  /test/:
    post:
      consumes:
      - application/json
      description: 描述
      parameters:
      - description: desc
        in: body
        name: body
        schema:
          $ref: '#/definitions/v1.TParam'
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/v1.TResponse'
            - properties:
                results:
                  $ref: '#/definitions/v1.TParam'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.TResponse2'
      summary: 接口测试
      tags:
      - 测试
  /users/:
    get:
      consumes:
      - application/json
      description: 暂时无权限/后需要登录
      parameters:
      - description: 页数
        in: query
        name: page
        type: string
      - description: 个数
        in: query
        name: size
        type: string
      responses:
        "200":
          description: '{"message":"成功获取用户列表!","results":[{"id":1,"nickname":"小明","account":"xiaoming","password":"123456","email":"","phone":"","isAdmin":false,"photoFile":"","createdTime":""}}]}'
          schema:
            type: string
        "400":
          description: '{"msg": "参数错误/获取用户列表失败!", "results": null}'
          schema:
            type: string
      summary: 获取用户列表
      tags:
      - 用户
    post:
      consumes:
      - application/json
      description: 只有管理员可以添加用户
      parameters:
      - description: desc
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/v1.AddUserParam'
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.Response'
            - properties:
                results:
                  $ref: '#/definitions/models.User'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Response'
      summary: 新增用户
      tags:
      - 用户
  /users/{id}/:
    delete:
      consumes:
      - application/json
      description: 只有管理员可以删除用户
      parameters:
      - description: 用户id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: '{"message":"删除完成！","results": null}'
          schema:
            type: string
        "400":
          description: '{"message": "参数错误/删除失败!", "results": null}'
          schema:
            type: string
      summary: 删除用户
      tags:
      - 用户
    get:
      consumes:
      - application/json
      description: 登陆后才允许获取用户信息
      parameters:
      - description: 用户id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: '{"message":"成功获取用户!","results":{"id":1,"nickname":"小明","account":"xiaoming","password":"123456","email":"","phone":"","isAdmin":false,"photoFile":"","createdTime":""}}}'
          schema:
            type: string
        "400":
          description: '{"msg": "参数错误/用户不存在!", "results": null}'
          schema:
            type: string
      summary: 获取用户
      tags:
      - 用户
    put:
      consumes:
      - application/json
      description: 只有管理员/或用户自己可以修改
      parameters:
      - default: "1"
        description: 用户id
        in: path
        name: id
        required: true
        type: string
      - description: desc
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/v1.ModifyUserParam'
      responses:
        "200":
          description: '{"message":"成功修改用户!","results":{"id":1,"nickname":"小明","account":"xiaoming","password":"123456","email":"","phone":"","isAdmin":false,"photoFile":"","createdTime":""}}}'
          schema:
            type: string
        "400":
          description: '{"msg": "参数错误/用户不存在!/用户修改失败!", "results": null}'
          schema:
            type: string
      summary: 修改用户
      tags:
      - 用户
  /users/{id}/photo/:
    put:
      consumes:
      - application/json
      description: 只有管理员/或用户自己可以修改
      parameters:
      - description: 用户id
        in: path
        name: id
        required: true
        type: string
      - description: 头像
        in: formData
        name: photoFile
        required: true
        type: file
      responses:
        "200":
          description: '{"message":"成功上传用户头像!","results":[{"id":1,"nickname":"小明","account":"xiaoming","password":"123456","email":"","phone":"","isAdmin":false,"photoFile":"","createdTime":""}}]}'
          schema:
            type: string
        "400":
          description: '{"msg": "参数错误/头像上传失败!", "results": null}'
          schema:
            type: string
      summary: 上传用户头像
      tags:
      - 用户
  /videos/:
    get:
      consumes:
      - application/json
      description: 无权限
      parameters:
      - description: 页数
        in: query
        name: page
        type: string
      - description: 个数
        in: query
        name: size
        type: string
      responses:
        "200":
          description: '{"message":"成功获取视频列表!","results":[{"id":1,"nickname":"小明","account":"xiaoming","password":"123456","email":"","phone":"","isAdmin":false,"photoFile":"","createdTime":""}}]}'
          schema:
            type: string
        "400":
          description: '{"msg": "参数错误/获取视频列表失败!", "results": null}'
          schema:
            type: string
      summary: 获取视频信息列表
      tags:
      - 视频
    post:
      consumes:
      - application/json
      description: 普通用户可上传
      parameters:
      - default: '{"title": "小明大战小黄", "desc": "test", "category": "电影", "label": "小明，小黄，动作，武打", "rm": "mp4"}'
        description: title(*标题)
        in: body
        name: body
        required: true
        schema:
          type: string
      responses:
        "200":
          description: '{"message":"创建视频完成!","results":{"id":1,"nickname":"小明","account":"xiaoming","password":"123456","email":"","phone":"","isAdmin":false,"photoFile":"","createdTime":""}}}'
          schema:
            type: string
        "400":
          description: '{"msg": "参数错误/创建失败!", "results": null}'
          schema:
            type: string
      summary: 上传视频信息
      tags:
      - 视频
  /videos/{id}/:
    delete:
      consumes:
      - application/json
      description: 只有管理员或作者可以删除视频
      parameters:
      - description: 视频id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: '{"message":"删除完成！","results": null}'
          schema:
            type: string
        "400":
          description: '{"msg": "参数错误/删除失败!", "results": null}'
          schema:
            type: string
      summary: 删除视频
      tags:
      - 视频
    get:
      consumes:
      - application/json
      parameters:
      - description: 视频id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: '{"message":"成功获取视频信息!","results":{"id":1,"nickname":"小明","account":"xiaoming","password":"123456","email":"","phone":"","isAdmin":false,"photoFile":"","createdTime":""}}}'
          schema:
            type: string
        "400":
          description: '{"msg": "参数错误/视频不存在!", "results": null}'
          schema:
            type: string
      summary: 获取视频信息
      tags:
      - 视频
    put:
      consumes:
      - application/json
      description: 只有管理员/或用户自己可以修改视频信息
      parameters:
      - default: '{"title": "小明大战小黄", "desc": "test", "category": "电影", "label": "小明，小黄，动作，武打", "rm": "mp4"}'
        description: title(*标题)
        in: body
        name: body
        required: true
        schema:
          type: string
      - default: '{"nickname": "小明", "account": "xiaoming", "password": "123456", "email": "", "phone": ""}'
        description: 用户信息
        in: body
        name: body
        required: true
        schema:
          type: string
      responses:
        "200":
          description: '{"message":"成功修改用户!","results":{"id":1,"nickname":"小明","account":"xiaoming","password":"123456","email":"","phone":"","isAdmin":false,"photoFile":"","createdTime":""}}}'
          schema:
            type: string
        "400":
          description: '{"msg": "参数错误/用户不存在!/用户修改失败!", "results": null}'
          schema:
            type: string
      summary: 修改视频
      tags:
      - 视频
swagger: "2.0"
